### ISSUE TITLE
SyntaxError: f-string: unmatched '['

### ISSUE THREAD

**Issue by ali0une** [regiellis/civitai-cli-manager#2]
Hi.

Not sure if i'm doing things right, but the command below give me an error.

Just started LM Studio server on port 5000

```
(venv) ali0une@Debian:~/whatever/civitai-cli-manager$ civitai-cli-manager --explain 619343 --service openai
Traceback (most recent call last):
  File "/whatever/civitai-cli-manager/venv/bin/civitai-cli-manager", line 5, in <module>
    from civitai_model_manager.cli import main
  File "/whatever/civitai-cli-manager/venv/lib/python3.11/site-packages/civitai_model_manager/cli.py", line 335
    "stats": f"{response["stats"].get("downloadCount", "")} downloads, {response["stats"].get('thumbsUpCount', '')} likes, {response["stats"].get('thumbsDownCount', '')} dislikes",
                          ^^^^^
SyntaxError: f-string: unmatched '['
```
This is my .env

```
#https://developer.civitai.com/docs/getting-started/setup-profile#create-an-api-key
CIVITAI_TOKEN=xxxxxxxxx
#/location/of/your/models/
MODELS_DIR=/whatever/models/

# http://localhost:11434 or http://host.docker.internal:11434
OLLAMA_API_BASE=http://localhost:5000
#OLLAMA_MODEL=tinydolphin # Tuned to tinydolphin..as best I could
HTML_OUT=False # Some models require HTML conversion, some don't
TEMP=0
TOP_P=0

#OPENAI_MODEL=gpt-4o-mini
#OPENAI_API_KEY= # sk-proj

#GROQ_MODEL=llama-3.1-70b-versatile
#GROQ_API_KEY=#//
```

**Comment by regiellis** [comment]
@ali0une4, no this was a oversight on my part in and had to be corrected in the code. The 0.5.1 release should fix the issue; Make to pip/pipx uninstall first then re-install before trying again. Also, if OLLAMA_API_BASE=http://localhost:5000, try OLLAMA_API_BASE=http://localhost:5000/v1/

**Comment by ali0une** [comment]
Thanks!

OK working with no error now ... but can't find the correct endpoint for LM Studio, i'm going to update [my other issue](https://github.com/regiellis/civitai-cli-manager/issues/1) about it.

Don't know how to `pip uninstall` when i `pip install .` , did `pip uninstall -r requirements.txt` but it did not suffice as i had same error ... had to delete venv and reinstall (sorry i'm python noob :-/ )
Please let me know!

**Comment by regiellis** [comment]
> Thanks!
> 
> OK working with no error now ... but can't find the correct endpoint for LM Studio, i'm going to update [my other issue](https://github.com/regiellis/civitai-cli-manager/issues/1) about it.
> 
> Don't know how to `pip uninstall` when i `pip install .` , did `pip uninstall -r requirements.txt` but it did not suffice as i had same error ... had to delete venv and reinstall (sorry i'm python noob :-/ ) Please let me know!

When you use `pip install .` the package is installed as `[package]-[version]` so in this case civitai_model_manager 0.5.0. you can do a `pip list` to find the name. PIP will install it by its package name wheres PIPX will install it by the name I am exposing....in this case "civitai-cli-manager". I recommend you install it via `pipx install .` PIPX will create a virtualenv for you and manage the package.

**Comment by ali0une** [comment]
Many thanks for this clear explaination!
